name: Our CI

on:
  pull_request:
  push:
    branches:
      - main  
      - other-branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
         python-version: "3.11"
      - name: Install Python Package
        run: python -m pip install .[test]
      - name: Run Tests
        run: python -m pytest
